version: 0.2

# env:
#   variables:
#     key: "value"
#     key: "value"

phases:
  # install:
  #   commands:
  #     - command
  #     - command

  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - git submodule init
      - git submodule update

  build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      # Replace the GA_TRACKING_ID placeholder with the tracking ID from the environment variable
      - sed -i "s/{{GA_TRACKING_ID}}/$GA_TRACKING_ID/" config.toml
      - grep gaid config.toml
      - hugo --ignoreCache

  post_build:
    commands:
      - cd $CODEBUILD_SRC_DIR/public
      - aws s3 cp --recursive . s3://$TARGET_S3_BUCKET/blog/

# artifacts:
#   files:
#     - location
#     - location
#   discard-paths: yes
#   base-directory: location
